apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prediction-worker
spec:
  template:
    spec:
      serviceAccountName: prediction-worker
      containers:
        - image: us-docker.pkg.dev/PROJECT_ID/kairyx/prediction-worker:latest
          command: ["uvicorn"]
          args: ["workers.prediction_worker_app:app", "--host", "0.0.0.0", "--port", "8080"]
          env:
            - name: APP_ENV
              value: prod
            - name: SERVICE_ROLE
              value: prediction-worker
          ports:
            - containerPort: 8080
